#!/bin/bash

cd utils
tar xzvf hetconvert-1.6.1.tar.gz
cd hetconvert
make
mv hetcnv ..
cd ..
build makeFtables
make
#
# make the Cello-arco-reference-1st instrument, MIDI number 43
instr="Cello-arco-reference-1st"
inum="43"
harmonics="10"
basetbl="500"
./makeFtables $instr $inum $harmonics $basetbl \
arco-ppC2 arco-ppG5 arco-ffC2 arco-ffG5

cd ../data
for x in Cello-arco-reference-1st
do
rm -f $x/*.asc
done
cd ..
unset instr inum harmonics basetbl